# EJEMPLO DE REFERENCIA — LIN-VER-001 Anexo F / LIN-K8S-001 Anexo A
# Overlay para ambiente de desarrollo (rama ONP_DESA)

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: frontend-nombre-sistema
    newName: registry.gitlab.onp.gob.pe/aplicaciones/nombre-sistema/frontend-nombre-sistema
    newTag: dev-latest

replicas:
  - name: frontend-nombre-sistema
    count: 1
