apiVersion: apps/v1
kind: Deployment
metadata:
  name: nombre-microservicio
spec:
  template:
    spec:
      containers:
        - name: nombre-microservicio
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
