management:
  otlp:
    tracing:
      endpoint: http://otel-collector.otel-qa.svc.cluster.local:4318/v1/traces
    logging:
      endpoint: http://otel-collector.otel-qa.svc.cluster.local:4318/v1/logs
  tracing:
    sampling:
      probability: 1.0

otel:
  resource:
    attributes: deployment.environment=quality

app:
  environment: quality
