# EJEMPLO DE REFERENCIA — LIN-VER-001 Anexo F / LIN-K8S-001 Anexo A
# Base Kustomize para el componente frontend Angular.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nombre-sistema

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  # - networkpolicy.yaml # obligatorio para servicios críticos (LIN-K8S-001 §11)

commonLabels:
  app.kubernetes.io/name: frontend-nombre-sistema
  app.kubernetes.io/part-of: nombre-sistema
  app.kubernetes.io/managed-by: kustomize
